### ISSUE TITLE
Trouble running in linux

### ISSUE THREAD

**Issue by TopView** [geraldoramos/nikola#21]
I'm having trouble getting this to run in Linux.

From https://nikola.site I clicked `download`, and then downloaded `Nikola_0.2.6_amd64.deb` into a working directory named `/nobak/Installers/Tesla/Nikola`

Then in terminal I run this to install it:  `sudo dpkg -i /nobak/Installers/Tesla/Nokola`

In the desktop menu I can see that the menu icon runs this:

	Name:		Nikola
	Command:	"/opt/Nikola/nikola/" %U
	Comment: 	Open source and unoffocial cross-platform desktop app to control tesla vehicles

But when I click on the desktop icon nothing happens.

I also tried running directly with:   `./opt/Nikola/nikola`  but get this error message:

> [31434:0610/180655.721386:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Nikola/chrome-sandbox is owned by root and has mode 4755.
> Trace/breakpoint trap
> 

I also noticed that the files in /opt/Nikola are all owned by root.

I'm not a huge Linux expert, so perhaps someone can tell me what I'm doing wrong, or what I might need to configure.

I'm running Debian Stretch 9.9 (x86-64); Cinnamon 3.2.7; Linux kernel 4.9.0-9-amd64

Thanks.

**Comment by TopView** [comment]
If it's any help, I have Chrome installed rather than Chromium.  I don't use it much, as I mostly use FireFox, but keep it around for the occasional web site that misbehaves under FireFox.

Also I found [this](https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md) mentioning that the SUID sandbox was almost but not completely removed.

**Comment by geraldoramos** [comment]
Can you try installing with sudo?  : `sudo dpkg -i /nobak/Installers/Tesla/Nokola`

**Comment by TopView** [comment]
> Can you try installing with sudo? : `sudo dpkg -i /nobak/Installers/Tesla/Nokola`

Thanks but sorry, I actually did use a sudo prefix, but unfortunately forgot here to mention it above.

I also tried both with and without sudo. 

I also just installed chomium [after I found that chrome and chromium are different programs](https://askubuntu.com/questions/179729/can-i-install-google-chrome-and-chromium-together) and thus could both run at the same time.

**Comment by geraldoramos** [comment]
I just released a new version (0.2.7), can you try? It worked fine for me (Ubuntu 18.04).

**Comment by volkerbradley** [comment]
Just downloaded Nikola-0.2.7-x86_64.AppImage to Ubuntu 18.04. 
In terminal:
a. chmod +x Nikola-0.2.7-x86_64.AppImage
b. ./Nikola-0.2.7-x86_64.AppImage
Login with Tesla credentials.
Seems to work for me.

**Comment by geraldoramos** [comment]
Closing until we hear from @TopView.

Thanks!

**Comment by TopView** [comment]
Thanks, but installed 0.2.7, but unfortunately no change, i.e. it still won't start from menu.  Also tried these:

[$cd /opt/Nikola
$nikola
$sudo nikola
[9093:0611/064740.988767:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Nikola/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
](url)

**Comment by geraldoramos** [comment]
Can you try the AppImage instead?
```
wget https://github.com/geraldoramos/nikola/releases/download/v0.2.7/Nikola-0.2.7-x86_64.AppImage
chmod +x Nikola-0.2.7-x86_64.AppImage
./Nikola-0.2.7-x86_64.AppImage
```
It worked here for me as well.

**Comment by TopView** [comment]
Also tried how volkerbradley had done this on Ubuntu, i.e. instead downloaded `Nikola-0.2.7-x86_64.AppImage` then:

```
$ chmod +x Nikola-0.2.7-x86_64.AppImage 
$ ./Nikola-0.2.7-x86_64.AppImage 
basename: extra operand ‘app/Nikola-0.2.7-x86_64.AppImage’
Try 'basename --help' for more information.
[9450:0611/070047.603018:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Nikola6rpUIs/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

```

**Comment by geraldoramos** [comment]
wow, sent messages at the same time. You tried what I've suggested..

**Comment by geraldoramos** [comment]
Will continue investigating.

**Comment by TopView** [comment]
:-) yes we were on the same page...  Now also tried w/ wget then chmod, etc, but still same error messages as before.

**Comment by TopView** [comment]
Ok, if I run ./Nikola-0.2.7-x86_64.AppImage --no-sandbox now it starts. I'll try to read more about this sandbox thing...

**Comment by TopView** [comment]
Here's more of a log and a screenshot:

```
$ ./Nikola-0.2.7-x86_64.AppImage --no-sandbox
07:11:51.007 › Nikola App starting...
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
07:11:53.347 › Checking for update
07:11:53.791 › Generated new staging user ID: d611d3b2-b250-506e-81c7-8fe23a3842d6
07:11:56.245 › Update for version 0.2.7 is not available (latest version: 0.2.7, downgrade is disallowed).
07:11:56.246 › checkForUpdatesAndNotify called, downloadPromise is null
07:14:48.503 › Hitting Tesla API on Tue Jun 11 2019 07:14:48 GMT-0700 (Pacific Daylight Time)
07:14:59.710 › Hitting Tesla API on Tue Jun 11 2019 07:14:59 GMT-0700 (Pacific Daylight Time)
07:15:10.615 › Hitting Tesla API on Tue Jun 11 2019 07:15:10 GMT-0700 (Pacific Daylight Time)
07:15:21.561 › Hitting Tesla API on Tue Jun 11 2019 07:15:21 GMT-0700 (Pacific Daylight Time)
07:15:32.448 › Hitting Tesla API on Tue Jun 11 2019 07:15:32 GMT-0700 (Pacific Daylight Time)
07:15:33.107 › Hitting Tesla API on Tue Jun 11 2019 07:15:33 GMT-0700 (Pacific Daylight Time)
07:15:36.673 › Hitting Tesla API on Tue Jun 11 2019 07:15:36 GMT-0700 (Pacific Daylight Time)
07:15:43.437 › Hitting Tesla API on Tue Jun 11 2019 07:15:43 GMT-0700 (Pacific Daylight Time)
07:15:54.443 › Hitting Tesla API on Tue Jun 11 2019 07:15:54 GMT-0700 (Pacific Daylight Time)
07:16:05.183 › Hitting Tesla API on Tue Jun 11 2019 07:16:05 GMT-0700 (Pacific Daylight Time)
07:16:15.861 › Hitting Tesla API on Tue Jun 11 2019 07:16:15 GMT-0700 (Pacific Daylight Time)
07:16:26.882 › Hitting Tesla API on Tue Jun 11 2019 07:16:26 GMT-0700 (Pacific Daylight Time)
07:16:37.661 › Hitting Tesla API on Tue Jun 11 2019 07:16:37 GMT-0700 (Pacific Daylight Time)

![screenshot-window-2019-06-11-071733](https://user-images.githubusercontent.com/2180096/59279661-2b4c4300-8c19-11e9-931e-1f7fea756db5.png)



```

**Comment by TopView** [comment]
This also start it.

```
$ cd /opt/Nikola
$ nikola --no-sandbox
```

Still trying to understand more about sandbox.  To be continued...

**Comment by volkerbradley** [comment]
Had the same messages.  Then closed the app and restarted it from the
Ubuntu menu.
Worked thereafter.

**Comment by TopView** [comment]
In both Chome and Chomium browsing to `chrome://gpu/` gives:

```
Log Messages
[10717:10717:0611/072603.939819:ERROR:sandbox_linux.cc(364)] : InitializeSandbox() called with multiple threads in process gpu-process.
```

(BTW, you can also browse to chrome://sandbox/ where it says, "You are adequately sandboxed.")

This led me to [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918433) possibly related Debian bug report.

**Comment by TopView** [comment]
@volkerbradley.  Still won't start from menu here.  But at least I have a workaround for now w/ --no-sandbox option.  Thanks for the help!

**Comment by fmonera** [comment]
Working on Kubuntu 18.10 without problems:
% sudo dpkg -i Nikola....
% nikola
